### ISSUE TITLE
Is this project open source?

### ISSUE THREAD

**Issue by lucasa** [generative-objects-org/GO-LowCode#3]
Hi!
When the source code will be published?

Thanks

**Comment by walteralmeida** [comment]
Hello Lucas,

The plan is to open by the end of the year. Actually working on writing the documentation, preparing learning materials and preparing an hosted SaaS version.

What are your needs ? How do you envision using Generative Objects ? Do you have any project you would want to do on Generative Objects ?

Warm Regards
Walter Almeida

**Comment by walteralmeida** [comment]
closed
